###
# Successful Login
POST https://flaskloginapp-h5dmamayeggtambe.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password123"
}

###
# Failed Login
POST https://flaskloginapp-h5dmamayeggtambe.canadacentral-01.azurewebsites.net/login
Content-Type: application/json

{
    "username": "admin",
    "password": "wrongpassword"
}

###
# Another Failed Login
POST https://flaskloginapp-h5dmamayeggtambe.canadacentral-01.azurewebsites.net//login
Content-Type: application/json

{
    "username": "user",
    "password": "anypassword"
} 